services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - internal_network

  producer:
    build:
      context: .
      target: producer
    networks:
      - internal_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    deploy:
      replicas: 1
    restart: on-failure

  consumer:
    build:
      context: .
      target: consumer
    networks:
      - internal_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  dashboard:
    build:
      context: .
      target: dashboard
    ports:
      - "${DASHBOARD_PORT:-8080}:8080"
    networks:
      - internal_network
      - external_network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: on-failure

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge
